Exception in thread Thread-1 (task):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/teikit/Desktop/Teikit/production/ui.py", line 27, in task
    open_all_lockers()
  File "/home/teikit/Desktop/Teikit/production/gpio_controller.py", line 34, in open_all_lockers
    turn_on_locker(locker_number)
  File "/home/teikit/Desktop/Teikit/production/gpio_controller.py", line 25, in turn_on_locker
    GPIO.output(pin, GPIO.HIGH)
RuntimeError: The GPIO channel has not been set up as an OUTPUT
UI cerrada correctamente
